services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
