spring.application.name=leetcode-progression-tracker

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
spring.ai.openai.api-key=${NVIDIA_NIM_API_KEY}
spring.ai.openai.chat.options.model=meta/llama-3.1-8b-instruct

logging.level.com.kylewelch.leetcode_progression_tracker=INFO
logging.level.org.springframework.jdbc.datasource.init=DEBUG