spring.application.name=leetcode-progression-tracker

spring.datasource.url=jdbc:h2:mem:leetcodeprogressiontracker
spring.datasource.username=dbuser
spring.datasource.password=dbpassword

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure OpenAI adapter to point to Ollama (for Qwen model)
spring.ai.openai.base-url=http://localhost:11434/v1
spring.ai.openai.api-key=${NVIDIA_NIM_API_KEY}
spring.ai.openai.chat.options.model=qwen2.5:0.5b

logging.level.com.kylewelch.leetcode_progression_tracker=INFO
logging.level.org.springframework.jdbc.datasource.init=DEBUG