spring.application.name=leetcode-progression-tracker

spring.datasource.url=jdbc:h2:mem:leetcodeprogressiontracker
spring.datasource.username=dbuser
spring.datasource.password=dbpassword

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.com.kylewelch.leetcode_progression_tracker=DEBUG